---
- name: Update apt cache and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
- name: Install common packages
  ansible.builtin.apt:
    name: [unattended-upgrades, rsyslog, ca-certificates, curl]
    state: present
- name: Set UTC timezone
  community.general.timezone:
    name: Etc/UTC
- name: Ensure rsyslog is enabled
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true
